# Fonts
# font_family      family='UbuntuMono Nerd Font Mono' postscript_name=UbuntuMonoNFM-Bold
# bold_font        family='UbuntuMono Nerd Font Mono' postscript_name=UbuntuMonoNFM-Bold
# italic_font      family='UbuntuMono Nerd Font Mono' style='Bold Italic'
# bold_italic_font family='UbuntuMono Nerd Font Mono' style='Bold Italic'
font_family      family='Inconsolata Nerd Font Mono' postscript_name=InconsolataNFM-Bold
bold_font        family='Inconsolata Nerd Font Mono' postscript_name=InconsolataNFM-Bold
italic_font      family='Inconsolata Nerd Font Mono' postscript_name=InconsolataNFM-Bold
bold_italic_font family='Inconsolata Nerd Font Mono' postscript_name=InconsolataNFM-Bold

symbol_map U+3000-U+9FFF Noto Sans Mono CJK JP Bold

narrow_symbols U+25CF,U+25CB 1

font_size 14.0

# Cursor customization
cursor_text_color #ffffff
cursor_shape beam
cursor_blink_interval 0

# Scrollback
scrollback_lines 2000
scrollback_fill_enlarged_window no

# Mouse
url_color #ffffff
url_style double
detect_urls yes
copy_on_select yes
strip_trailing_spaces smart
focus_follows_mouse yes

#Terminal bell
enable_audio_bell no

# Window layout
remember_window_size no
initial_window_width 140c
initial_window_height 40c

# Tab Bar
tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 2
tab_switch_strategy previous
tab_powerline_style round
active_tab_foreground   #82AAFF
active_tab_background   #3B4261
active_tab_font_style   bold
inactive_tab_foreground #545C7E
inactive_tab_background #2F334D
inactive_tab_font_style normal
tab_bar_background #1e2030
tab_bar_margin_color none

# Color scheme
foreground #c0caf5
background #24283b
selection_foreground #c0caf5
selection_background #2e3c64

# Color table
color0 #1d202f
color1 #f7768e
color2 #9ece6a
color3 #e0af68
color4 #7aa2f7
color5 #bb9af7
color6 #7dcfff
color7 #a9b1d6

color8 #414868
color9 #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5

# Advanced
close_on_child_death yes

# shell_integration
shell_integration enabled
shell_integration no-cursor
