CompileFlags:
  Add: [
    -Wall,
    -Wextra,
    -pedantic,
  ]
---
If:
  PathMatch: [.+\.h$, .+\.c$ ]
CompileFlags:
  Add: [
    -std=c23,
  ]
---
If:
  PathMatch: [.+\.hpp$, .+\.cc$, .+\.cxx$, .+\.cpp$ ]
CompileFlags:
  Add: [
    -std=c++23,
  ]
