source $VIMRUNTIME/delmenu.vim

set columns=120
set lines=40
let &guifont = "Ubuntu Mono:b:h14"
let &guifontwide = "源真ゴシック等幅_Bold:h12"
set guioptions+=M
set guioptions-=e
set guioptions-=g
set guioptions-=m
set guioptions-=r
set guioptions-=L
set guioptions-=t
set guioptions-=T
