source $VIMRUNTIME/defaults.vim

set viminfo=
set noundofile
set nobackup
set noswapfile

set helplang=ja,en
set number
set signcolumn=number
set tabstop=4
set shiftwidth=4
set expandtab
set belloff=all
set fileformats=unix,dos
set fileformat=unix
set fileencodings=utf-8,sjis
set fileencoding=utf-8
set encoding=utf-8
set termguicolors
set cursorline
set hlsearch
set ignorecase
set smartcase
set smartindent
set smarttab
set incsearch
set splitbelow
set splitright
set hidden
set laststatus=2
set pumheight=10
set wildmenu
set wildoptions=pum
set wildmode=longest,full
set backspace=indent,eol,start
let &shell = has("win32") ? "powershell -nologo" : "bash"

"let &t_ut = ''
let &fillchars = "vert:\u2502,fold:-,eob:\x20"

syntax enable

let s:jetpackfile = expand("<sfile>:p:h") .. "/pack/jetpack/opt/vim-jetpack/plugin/jetpack.vim"
let s:jetpackurl = "https://raw.githubusercontent.com/tani/vim-jetpack/master/plugin/jetpack.vim"
if !filereadable(s:jetpackfile)
    call system(printf("curl -fsSLo %s --create-dirs %s", s:jetpackfile, s:jetpackurl))
endif

let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1

packadd matchit
packadd termdebug

packadd vim-jetpack
call jetpack#begin()
call jetpack#add("tani/vim-jetpack", { "opt": v:true })
call jetpack#add("vim-jp/vimdoc-ja")
call jetpack#add("prabirshrestha/vim-lsp")
call jetpack#add("prabirshrestha/asyncomplete.vim")
call jetpack#add("prabirshrestha/asyncomplete-lsp.vim")
call jetpack#add("mattn/vim-lsp-settings")
call jetpack#add("hrsh7th/vim-vsnip")
call jetpack#add("hrsh7th/vim-vsnip-integ")
call jetpack#add("lambdalisue/fern.vim")
call jetpack#add("lambdalisue/fern-git-status.vim")
call jetpack#add("lambdalisue/fern-renderer-nerdfont.vim")
call jetpack#add("lambdalisue/fern-hijack.vim")
call jetpack#add("lambdalisue/nerdfont.vim")
call jetpack#add("itchyny/lightline.vim")
call jetpack#add("luochen1990/rainbow")
call jetpack#add("dracula/vim", { "as": "dracula" })
call jetpack#end()

colorscheme chester

for elem in sort(split(globpath(&runtimepath, "config.d/*.vim")))
    execute "source" elem
endfor
