source $VIMRUNTIME/defaults.vim

let &viminfofile = expand("<sfile>:p:h") .. "/viminfo"
set noundofile
set nobackup
set noswapfile

set backspace=indent,eol,start
set belloff=all
set cursorline
set encoding=utf-8
set expandtab
set fileencoding=utf-8
set fileencodings=utf-8,sjis
set fileformat=unix
set fileformats=unix,dos
set helplang=ja,en
set hidden
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set list
set number
set pumheight=10
set shiftwidth=4
set signcolumn=number
set smartcase
set smartindent
set smarttab
set splitbelow
set splitright
set tabstop=4
set termguicolors
set wildmenu
set wildmode=longest,full
set wildoptions=pum

let &fillchars = "vert:\u2502,fold:-,eob:\u20"
let &listchars = "tab:> ,trail:-,nbsp:+"
let &shell = has("win32") ? "powershell -nologo" : "bash"
let mapleader = " "
let &t_Cs = "\e[4:3m"
let &t_Ce = "\e[4:0m"

syntax enable

let s:jetpackfile = expand("<sfile>:p:h") .. "/pack/jetpack/opt/vim-jetpack/plugin/jetpack.vim"
let s:jetpackurl = "https://raw.githubusercontent.com/tani/vim-jetpack/master/plugin/jetpack.vim"
if !filereadable(s:jetpackfile)
    call system(printf("curl -fsSLo %s --create-dirs %s", s:jetpackfile, s:jetpackurl))
endif

let g:loaded_gzip = 1
let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1
let g:loaded_tar = 1
let g:loaded_tarPlugin = 1
let g:loaded_zip = 1
let g:loaded_zipPlugin = 1

packadd termdebug
packadd vim-jetpack
call jetpack#begin()
call jetpack#add("tani/vim-jetpack", { "opt": v:true })

call jetpack#add("dracula/vim", { "as": "dracula" })
call jetpack#add("easymotion/vim-easymotion")
call jetpack#add("hrsh7th/vim-vsnip")
call jetpack#add("hrsh7th/vim-vsnip-integ")
call jetpack#add("itchyny/lightline.vim")
call jetpack#add("jiangmiao/auto-pairs")
call jetpack#add("lambdalisue/fern-git-status.vim")
call jetpack#add("lambdalisue/fern-hijack.vim")
call jetpack#add("lambdalisue/fern-renderer-nerdfont.vim")
call jetpack#add("lambdalisue/fern.vim")
call jetpack#add("lambdalisue/nerdfont.vim")
call jetpack#add("luochen1990/rainbow")
call jetpack#add("mattn/vim-lsp-settings")
call jetpack#add("prabirshrestha/asyncomplete-lsp.vim")
call jetpack#add("prabirshrestha/asyncomplete.vim")
call jetpack#add("prabirshrestha/vim-lsp")
call jetpack#add("rust-lang/rust.vim")
call jetpack#add("vim-jp/vimdoc-ja")
call jetpack#end()

for elem in sort(split(globpath(&runtimepath, "config.d/*.vim")))
    execute "source" elem
endfor
defcompile

colorscheme chester
