source $VIMRUNTIME/delmenu.vim

set columns=130
set lines=30
let &guifont = "UbuntuMono Nerd Font Mono:b:h14,Consolas:b:h14"
let &guifontwide = "源真ゴシック等幅_Bold:h12,MS_Gothic:b:h12"
set clipboard=unnamed
set guioptions+=M
set guioptions-=e
set guioptions-=g
set guioptions-=m
set guioptions-=r
set guioptions-=L
set guioptions-=t
set guioptions-=T
