vim.g.mapleader = " "
vim.api.nvim_set_option_value("clipboard", "unnamed,unnamedplus", {})
vim.api.nvim_set_option_value("cmdheight", vim.g.vscode and 1 or 0, {})
vim.api.nvim_set_option_value("cursorline", true, {})
vim.api.nvim_set_option_value("encoding", "utf-8", {})
vim.api.nvim_set_option_value("expandtab", true, {})
vim.api.nvim_set_option_value("fileencoding", "utf-8", {})
vim.api.nvim_set_option_value("fileencodings", "utf-8,sjis,cp932", {})
vim.api.nvim_set_option_value("fileformat", "unix", {})
vim.api.nvim_set_option_value("fileformats", "unix,dos", {})
vim.api.nvim_set_option_value("fillchars", "vert:\u{2502},fold:\u{ff65},eob:\u{20}", {})
vim.api.nvim_set_option_value("grepprg", "rg --vimgrep -uu --no-heading --smart-case", {})
vim.api.nvim_set_option_value("helplang", "ja,en", {})
vim.api.nvim_set_option_value("hidden", true, {})
vim.api.nvim_set_option_value("hlsearch", true, {})
vim.api.nvim_set_option_value("ignorecase", true, {})
vim.api.nvim_set_option_value("incsearch", true, {})
vim.api.nvim_set_option_value("laststatus", 3, {})
vim.api.nvim_set_option_value("list", true, {})
vim.api.nvim_set_option_value("listchars", "tab:\u{2192}\u{0020},trail:\u{00b7},nbsp:\u{002b},space:\u{00b7}", {})
vim.api.nvim_set_option_value("number", true, {})
vim.api.nvim_set_option_value("pumblend", 5, {})
vim.api.nvim_set_option_value("pumheight", 10, {})
vim.api.nvim_set_option_value("relativenumber", false, {})
vim.api.nvim_set_option_value("scrolloff", 5, {})
vim.api.nvim_set_option_value("shiftwidth", 4, {})
vim.api.nvim_set_option_value("signcolumn", "number", {})
vim.api.nvim_set_option_value("smartcase", true, {})
vim.api.nvim_set_option_value("smartindent", true, {})
vim.api.nvim_set_option_value("smarttab", true, {})
vim.api.nvim_set_option_value("splitbelow", true, {})
vim.api.nvim_set_option_value("splitright", true, {})
vim.api.nvim_set_option_value("tabstop", 4, {})
vim.api.nvim_set_option_value("termguicolors", true, {})
vim.api.nvim_set_option_value("updatetime", 500, {})
vim.api.nvim_set_option_value("virtualedit", "block,onemore", {})
vim.api.nvim_set_option_value("wildmenu", true, {})
vim.api.nvim_set_option_value("wildmode", "longest,full", {})
vim.api.nvim_set_option_value("wildoptions", "pum", {})
vim.api.nvim_set_option_value("winblend", 10, {})
-- 様々なプラグインが対応したら一括で設定できるwinborderオプションを使用する予定
-- vim.api.nvim_set_option_value("winborder", "rounded", {})

if vim.loop.os_uname().sysname == "Windows_NT" then
    vim.api.nvim_set_option_value("shell", vim.fn.executable("pwsh") and "pwsh" or "powershell", {})
    vim.api.nvim_set_option_value(
        "shellcmdflag",
        "-NoLogo -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;$PSDefaultParameterValues['*:Encoding']='utf8';",
        {}
    )
    vim.api.nvim_set_option_value("shellpipe", '2>&1 | %%{ "$_" } | Tee-Object %s; exit $LastExitCode', {})
    vim.api.nvim_set_option_value("shellquote", "", {})
    vim.api.nvim_set_option_value("shellredir", '2>&1 | %%{ "$_" } | Out-File %s; exit $LastExitCode', {})
    vim.api.nvim_set_option_value("shellxquote", "", {})
end
