"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 4
# console_title_template = "{{ if .WSL }}\ue712 {{ end }}{{ .PWD }}"
console_title_template = "{{ end }}{{ .PWD }}"

[palette]
foreground        = "#C0CAF5"
background        = "#24283B"
background_bright = "#3B4261"
background_dark   = "#1F2335"
black             = "#15161E"
black_bright      = "#414868"
blue              = "#7AA2F7"
blue_bright       = "#8DB0FF"
cyan              = "#7DCFFF"
cyan_bright       = "#A4DAFF"
green             = "#9ECE6A"
green_bright      = "#9FE044"
magenta           = "#BB9AF7"
magenta_bright    = "#C7A9FF"
red               = "#F7768E"
red_bright        = "#FF899D"
white             = "#A9B1D6"
white_bright      = "#C0CAF5"
yellow            = "#E0AF68"
yellow_bright     = "#FABA4A"

[[blocks]]
type = "prompt"
alignment = "left"

  [[blocks.segments]]
  type = "session"
  style = "diamond"
  leading_diamond = "\uE0B6"  # 
  trailing_diamond = "\uE0B4" # 
  foreground = "p:background"
  background = "p:blue"
  templates = ["{{ .UserName }}"]

  [[blocks.segments]]
  type = "path"
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = "\uE0B4" # 
  foreground = "p:blue"
  background = "p:background_bright"
  templates = ["\u2800", "{{ path .Path .Location }}"]

    [blocks.segments.properties]
    style = "mixed"
    mixed_threshold = 10
    folder_separator_icon = "/"
    home_icon = "~"

  [[blocks.segments]]
  type = "git"
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = "\uE0B4" # 
  foreground = "p:background"
  background = "p:blue"
  templates = [
    # Braille Pattern Blank
    "\u2800",
    "{{ if .Ref }}{{ url .Ref .UpstreamURL }}{{ end }}",
    #  
    "{{ if or (ne .Ahead 0) (ne .Behind 0)}} [\uF062{{ .Ahead }} \uF063{{ .Behind }}]{{ end }}",
    #   
    "{{ if .Staging.Changed }} [<p:green>\uF067{{ .Staging.Added }} \uF068{{ .Staging.Deleted }} \uF069{{ .Staging.Modified }}</>]{{ end }}",
    #   
    "{{ if .Working.Changed }} [<p:red>\uF067{{ .Working.Untracked }} \uF068{{ .Working.Deleted }} \uF069{{ .Working.Modified }}</>]{{ end }}",
  ]

    [blocks.segments.properties]
    branch_max_length = 0.0
    fetch_status = true
    fetch_upstream_icon = true

      [blocks.segments.properties.untracked_modes]
      "*" = "all"

  [[blocks.segments]]
  type = "python"
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = "\uE0B4" # 
  foreground = "p:background"
  background = "p:yellow"
  # Braille Pattern Blank 󰌠
  templates = ["\u2800", "\U000F0320", "{{ .Full }}"]

  [[blocks.segments]]
  type = "node"
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = "\uE0B4" # 
  foreground = "p:background"
  background = "p:yellow"
  # Braille Pattern Blank 󰎙
  templates = ["\u2800", "\U000F0399", "{{ .Full }}"]

    [blocks.segments.properties]
    extensions = ["package.json"]

  [[blocks.segments]]
  type = "deno"
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = "\uE0B4" # 
  foreground = "p:background"
  background = "p:yellow"
  # Braille Pattern Blank 
  templates = ["\u2800", "\uE7C0", "{{ .Full }}"]

    [blocks.segments.properties]
    extensions = ["deno.json"]

  [[blocks.segments]]
  type = "root"
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = "\uE0B4" # 
  foreground = "p:background"
  background = "p:yellow"
  template = "\uF0E7" # 
