name: build-install-scripts

on:
  push:
    branches: ["develop"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: ls
        run: ls
