name: build-install-scripts

on:
  push:
    branches: ["develop"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: check python version 1
        run: python --version

      - name: setup python
        uses: actions/setup-python@v5

      - name: check python version 2
        run: python --version
